version: 0.2
phases:
 pre_build:
 commands:
   - echo Entered prebuild phase
 build:
 commands:
  - echo Build started on
  - ./mvnw.cmd clean package -DskipTests
 commands:
 - echo build completed
artifacts:
 files:
 - target/bilar-0.0.1-SNAPSHOT.jar
discard-paths: yes